#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
write_files:
  - path: /root/docker-compose.yaml
    content: |
      version: "3.4"
      services:
        db:
          image: postgres
          environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          networks:
            - djangonetwork
        web:
          image: gamadorh1993/truehouse:latest
          restart: always
          ports:
            - "8000:8000"
          environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
          depends_on:
            - db
          links:
            - db:db
          networks:
            - djangonetwork
          command: bash -c "python true_house/manage.py migrate && python true_house/manage.py runserver 0.0.0.0:8000"
      networks:
        djangonetwork:
          driver: bridge

runcmd:
  - docker-compose -f /root/docker-compose.yaml up -d db
  - docker-compose -f /root/docker-compose.yaml up -d web
